#!/bin/bash

readonly this_dir=$(dirname -- "$(readlink -e -- "$0")")
cd -- "$this_dir" || exit 1

activate() {
	if ! [[ -d .venv ]]; then
		python3 -m venv --system-site-packages --symlinks .venv
		source .venv/bin/activate
		pip3 install -r requirements.txt
	else
		source .venv/bin/activate
	fi
}

# If .novenv file exist in directory, run script without virtual environment
if ! [[ -f .novenv ]] ; then
	activate
fi

exec python3 cli.py "$@"
